export const predefinedColors = [
  { name: "White", value: "#ffffff" },
  { name: "Light Gray", value: "#f3f4f6" },
  { name: "Cream", value: "#fdf6e3" },
  { name: "Mint", value: "#f0fff4" },
  { name: "Light Blue", value: "#f0f9ff" },
  { name: "Lavender", value: "#faf5ff" },
  { name: "Sepia", value: "#fdf2e9" },
  { name: "Night", value: "#1a1a1a" },
  { name: "Soft Beige", value: "#f5f5dc" },
  { name: "Light Sepia", value: "#f4ecd8" },
  { name: "Warm Gray", value: "#e5e5e5" },
  { name: "Pale Yellow", value: "#fffff0" },
  { name: "Light Brown", value: "#d2b48c" },
  { name: "Off White", value: "#faf0e6" },
];

export const predefinedTextColors = [
  { name: "Black", value: "#000000" },
  { name: "Dark Gray", value: "#333333" },
  { name: "Gray", value: "#666666" },
  { name: "Light Gray", value: "#999999" },
  { name: "Dark Blue", value: "#1a365d" },
  { name: "Navy", value: "#1e3a8a" },
  { name: "Dark Green", value: "#064e3b" },
  { name: "Dark Brown", value: "#78350f" },
  { name: "White", value: "#ffffff" },
  { name: "Slate", value: "#475569" },
  { name: "Dark Red", value: "#7f1d1d" },
  { name: "Dark Purple", value: "#581c87" },
];
